// <auto-generated />
package AST;
import java.util.*;
import AST.compareOp; 
import AST.findOne; 
 public class compare
  {
	public compare (String left,compareOp thecompareOp) {
		 this.left = left; 
		 this.thecompareOp = thecompareOp; 
}

	public compare () {
}

	public String left; 
	public compareOp thecompareOp; 
	public Optional<String> NUMBER = Optional.empty(); 
	public Optional<String> STRINGLITERAL = Optional.empty(); 
	public Optional<String> IDENTIFIER = Optional.empty(); 
	public Optional<findOne> findOne = Optional.empty(); 
}
