// <auto-generated />
package AST;
import java.util.*;
import AST.field; 
 public class create
  {
	public create (String name) {
		 this.name = name; 
}

	public create () {
}

	public String name; 
	public LinkedList<field> field = new LinkedList<field>(); 
}
