// <auto-generated />
package AST;
import java.util.*;
import AST.values; 
import AST.findOne; 
 public class delete
  {
	public delete (String name) {
		 this.name = name; 
}

	public delete () {
}

	public String name; 
	public LinkedList<values> values = new LinkedList<values>(); 
	public LinkedList<findOne> findOne = new LinkedList<findOne>(); 
}
