// <auto-generated />
package AST;
import java.util.*;
import AST.type; 
 public class field
  {
	public field (type type,String name) {
		 this.type = type; 
		 this.name = name; 
}

	public field () {
}

	public type type; 
	public String name; 
}
