// <auto-generated />
package AST;
import java.util.*;
import AST.where; 
import AST.return_; 
 public class from
  {
	public from (String name) {
		 this.name = name; 
}

	public from () {
}

	public String name; 
	public Optional<where> where = Optional.empty(); 
	public Optional<return_> return_ = Optional.empty(); 
}
