// <auto-generated />
package AST;
import java.util.*;
import AST.values; 
 public class insert
  {
	public insert (String name) {
		 this.name = name; 
}

	public insert () {
}

	public String name; 
	public LinkedList<values> values = new LinkedList<values>(); 
}
