// <auto-generated />
package AST;
import java.util.*;
 public class returnName
  {
	public returnName (String name) {
		 this.name = name; 
}

	public returnName () {
}

	public String name; 
	public LinkedList<String> field = new LinkedList<String>(); 
}
