// <auto-generated />
package AST;
import java.util.*;
import AST.returnName; 
 public class return_
  {
	public return_ () {
}

	public LinkedList<returnName> returnName = new LinkedList<returnName>(); 
}
