// <auto-generated />
package AST;
import java.util.*;
import AST.statement; 
 public class sharQL
  {
	public sharQL () {
}

	public LinkedList<statement> statement = new LinkedList<statement>(); 
}
