// <auto-generated />
package AST;
import java.util.*;
import AST.create; 
import AST.insert; 
import AST.delete; 
import AST.from; 
 public class statement
  {
	public statement () {
}

	public Optional<create> create = Optional.empty(); 
	public Optional<insert> insert = Optional.empty(); 
	public Optional<delete> delete = Optional.empty(); 
	public Optional<from> from = Optional.empty(); 
}
