// <auto-generated />
package AST;
import java.util.*;
import AST.string_ORwholeNumberORdecimalNumber; 
 public class type
  {
	public type (boolean enum_,boolean list) {
		 this.enum_ = enum_; 
		 this.list = list; 
}

	public type () {
}

	public boolean enum_; 
	public LinkedList<String> enumValue = new LinkedList<String>(); 
	public boolean list; 
	public LinkedList<String> tableName = new LinkedList<String>(); 
	public Optional<string_ORwholeNumberORdecimalNumber> thestring_ORwholeNumberORdecimalNumber = Optional.empty(); 
}
