// <auto-generated />
package AST;
import java.util.*;
import AST.findOne; 
import AST.valueList; 
 public class value
  {
	public value () {
}

	public Optional<String> NUMBER = Optional.empty(); 
	public Optional<String> STRINGLITERAL = Optional.empty(); 
	public Optional<String> name = Optional.empty(); 
	public Optional<findOne> findOne = Optional.empty(); 
	public Optional<valueList> valueList = Optional.empty(); 
}
