// <auto-generated />
import java.util.*;
 public class Token
  {
     public enum TokenTypes
      {
          IDENTIFIER,
          NUMBER,
          INDENT,DEDENT,
          NEWLINE,
          STRINGLITERAL,
          CREATE,
          TABLE,
          ENUM,
          STRING,
          WHOLENUMBER,
          DECIMALNUMBER,
          LIST,
          INSERT,
          FINDONE,
          DELETE,
          FROM,
          WHERE,
          RETURN,
          OPENPAREN,
          COMMA,
          CLOSEPAREN,
          LESSTHAN,
          GREATERTHAN,
          LEFTBRACE,
          RIGHTBRACE,
          EQUAL,
          NOTEQUAL,
          LESSTHANEQUAL,
          GREATERTHANEQUAL,
          DOT,
      }
    public Optional<String> Value;
    public TokenTypes Type;
    public int ColumnNumber;
    public int LineNumber;

    public Token (TokenTypes type, int line, int column) {
		this(type,line,column,Optional.empty());
      }
    public Token (TokenTypes type, int line, int column,String val) {
		this(type,line,column,Optional.of(val));
      }

    private Token (TokenTypes type, int line, int column,Optional<String> val)
      {
      this.Type = type;
      this.Value = val;
      this.LineNumber = line;
      this.ColumnNumber = column;
      }

    public String toString()
      {
          return Type + " " + Value.orElse("") + " @ " + LineNumber + "," + ColumnNumber;
      }
}
